### PR TITLE
Bugfix/no route found

### LINKED ISSUE #29: No route found error when saving edits on Edit Partner page
Attempted to save partner (url: http://coverd.localhost:8080/#/partners/1) after making changes to the partner information.  Received error message: 

Exception: No route found for "PATCH /api/partners/1": Method Not Allowed (Allow: GET)

Two different attempts to change contact title and partner type produced the error.

### PR DESCRIPTION
**Pull request by ericpoe**
This closes #29 

An update method was needed to be created for `PartnerController` that would overwrite the parent, `StorageLocationController`, but additional methods had to be created to update the address and various optionlists.

Also removed the Address title from the Partner Edit view since each Partner only has one address.

### CODE REVIEW

File: src/Controller/PartnerController.php [hunk 1]
```diff
@@ -39,6 +41,36 @@ public function show(Request $request, int $id): JsonResponse
...
+     * @throws \Exception
+     */
+    public function update(Request $request, $id)
+    {
+        $params = $this->getParams($request);
+
+        $partner = $this->getPartnerById($id);
+        $partner->applyChangesFromArray($params);
+
+        if ($params['distributionMethod']['id']) {
```
Comment (akoebbe) [inline src/Controller/PartnerController.php]: Put these two conditions in an `applyChangesFromArray` override in this class. Make sense?
